<a href="https://colab.research.google.com/github/jgamel/learn_n_dev/blob/python_programming/numpy_guide.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Tutorial

This Notebook is a comprehensive reveiw of the many different features within the Numpy Module.

In [105]:
import numpy as np

## Creating Arrays

In [106]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)

### Initial Placeholders

In [107]:
np.zeros((3,4)) #Create an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [108]:
np.ones((2,3,4),dtype=np.int16) #Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [109]:
d = np.arange(10,25,5) #Create an array of evenly spaced values (step value)
d

array([10, 15, 20])

In [110]:
np.linspace(0,2,9) #Create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [111]:
e = np.full((2,2),7) #Create a constant array
e

array([[7, 7],
       [7, 7]])

In [112]:
f = np.eye(2) #Create a 2X2 identity matrix
f

array([[1., 0.],
       [0., 1.]])

In [113]:
np.random.random((2,2)) #Create an array with random values

array([[0.5103108 , 0.95200002],
       [0.50687995, 0.06015856]])

In [114]:
np.empty((3,2)) #Create an empty array

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

###array initialization

In [203]:
np.array([2, 3, 4])             # direct initialization

array([2, 3, 4])

In [204]:
np.empty(20, dtype=np.float32)  # single precision array of size 20

array([2.9601393e-36, 0.0000000e+00, 6.4459729e-44, 1.3872855e-43,
       1.5554413e-43, 1.5134023e-43, 1.6395192e-43, 1.5274153e-43,
       1.5414283e-43, 1.3312335e-43, 1.6114932e-43, 1.6255062e-43,
       1.3592595e-43, 1.3872855e-43, 1.4993894e-43, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
      dtype=float32)

In [205]:
np.zeros(200)                   # initialize 200 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [206]:
np.ones((3,3), dtype=np.int32)  # 3 x 3 integer matrix with ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [207]:
np.eye(200)                     # ones on the diagonal

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [208]:
np.zeros_like(a)                # array with zeros and the shape of a

array([0, 0, 0])

In [209]:
np.linspace(0., 10., 100)       # 100 points from 0 to 10

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [210]:
np.arange(0, 100, 2)            # points from 0 to <100 with step 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [211]:
np.logspace(-5, 2, 100)         # 100 log-spaced from 1e-5 -> 1e2

array([1.00000000e-05, 1.17681195e-05, 1.38488637e-05, 1.62975083e-05,
       1.91791026e-05, 2.25701972e-05, 2.65608778e-05, 3.12571585e-05,
       3.67837977e-05, 4.32876128e-05, 5.09413801e-05, 5.99484250e-05,
       7.05480231e-05, 8.30217568e-05, 9.77009957e-05, 1.14975700e-04,
       1.35304777e-04, 1.59228279e-04, 1.87381742e-04, 2.20513074e-04,
       2.59502421e-04, 3.05385551e-04, 3.59381366e-04, 4.22924287e-04,
       4.97702356e-04, 5.85702082e-04, 6.89261210e-04, 8.11130831e-04,
       9.54548457e-04, 1.12332403e-03, 1.32194115e-03, 1.55567614e-03,
       1.83073828e-03, 2.15443469e-03, 2.53536449e-03, 2.98364724e-03,
       3.51119173e-03, 4.13201240e-03, 4.86260158e-03, 5.72236766e-03,
       6.73415066e-03, 7.92482898e-03, 9.32603347e-03, 1.09749877e-02,
       1.29154967e-02, 1.51991108e-02, 1.78864953e-02, 2.10490414e-02,
       2.47707636e-02, 2.91505306e-02, 3.43046929e-02, 4.03701726e-02,
       4.75081016e-02, 5.59081018e-02, 6.57933225e-02, 7.74263683e-02,
      

In [212]:
np.copy(a)                      # copy array to new memory

array([1, 2, 3])

## I/O

###Saving & Loading On Disk

In [115]:
np.save('my_array', a)

In [116]:
np.savez('array.npz', a, b)

In [117]:
np.savetxt('array.txt', a,)

In [118]:
np.load('my_array.npy')

array([1, 2, 3])

In [119]:
np.load('array.npz')

In [120]:
np.loadtxt('array.txt')

array([1., 2., 3.])

##Asking For Help

In [121]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


##Inspecting Your Array

In [122]:
a.shape #Array dimensions

(3,)

In [123]:
len(a) #Length of array

3

In [124]:
b.ndim #Number of array dimensions

2

In [125]:
e.size #Number of array elements

4

In [126]:
b.dtype #Data type of array elements

dtype('float64')

In [127]:
b.dtype.name #Name of data type

'float64'

In [128]:
b.astype(int) #Convert an array to a different type


array([[1, 2, 3],
       [4, 5, 6]])

##Data Types

In [129]:
np.int64 #Signed 64-bit integer types

numpy.int64

In [130]:
np.float32 #Standard double-precision floating point

numpy.float32

In [131]:
np.complex #Complex numbers represented by 128 floats

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


complex

In [132]:
np.bool #Boolean type storing TRUE and FALSE values Numpy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


bool

In [133]:
np.object #Python object type

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


object

In [134]:
np.string_ #Fixed-length string type

numpy.bytes_

In [135]:
np.unicode_ #Fixed-length unicode type

numpy.str_

##Array Mathematics

###Arithmetic Operations

In [136]:
a - b #Subtraction

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [137]:
np.subtract(a,b) #Subtraction

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [138]:
b + a #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [139]:
np.add(b,a) #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [140]:
a / b #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [141]:
np.divide(a,b) #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [142]:
a * b #Multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [143]:
np.multiply(a,b) #Multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [144]:
np.exp(b) #Exponentiation

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [145]:
np.sqrt(b) #Square root

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [146]:
np.sin(a) #Print sines of an array

array([0.84147098, 0.90929743, 0.14112001])

In [147]:
np.cos(b) #Element-wise cosine

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [148]:
np.log(a) #Element-wise natural logarithm

array([0.        , 0.69314718, 1.09861229])

In [149]:
e.dot(f) #Dot product

array([[7., 7.],
       [7., 7.]])

###Comparison

In [150]:
a == b #Element-wise comparison

array([[False,  True,  True],
       [False, False, False]])

In [151]:
a < 2 #Element-wise comparison

array([ True, False, False])

In [152]:
np.array_equal(a, b) #Array-wise comparison

False

###Aggregate Functions

In [153]:
a.sum() #Array-wise sum

6

In [154]:
a.min() #Array-wise minimum value

1

In [155]:
b.max(axis=0) #Maximum value of an array row

array([4., 5., 6.])

In [156]:
b.cumsum(axis=1) #Cumulative sum of the elements

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [157]:
a.mean() #Mean

2.0

In [158]:
np.median(b) #Median

3.5

In [159]:
np.corrcoef(a) #Correlation coefficient

1.0

In [160]:
np.std(b) #Standard deviation

1.5920810978785667

##Copying Arrays

In [161]:
h = a.view() #Create a view of the array with the same data

In [162]:
np.copy(a) #Create a copy of the array

array([1, 2, 3])

In [163]:
h = a.copy() #Create a deep copy of the array
h

array([1, 2, 3])

##Sorting Arrays

In [164]:
a.sort() #Sort an array
a

array([1, 2, 3])

In [165]:
c.sort(axis=0) #Sort the elements of an array's axis
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

##Subsetting, Slicing, Indexing

Subsetting

In [166]:
a[2] #Select the element at the 2nd index

3

In [167]:
b[1,2] #Select the element at row 1 column 2 (equivalent to b[1][2])


6.0

Slicing

In [168]:
a[0:2]

array([1, 2])

In [169]:
b[0:2,1]

array([2., 5.])

In [170]:
b[:1] #Select all items at row 0 (equivalent to b[0:1, :])

array([[1.5, 2. , 3. ]])

In [171]:
c[1,...] #Same as [1,:,:]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [172]:
a[ : :-1] #Reversed array a array([3, 2, 1])

array([3, 2, 1])

Boolean Indexing

In [173]:
a[a<2] #Select elements from a less than 2

array([1])

Fancy Indexing

In [174]:
b[[1, 0, 1, 0],[0, 1, 2, 0]] #Select elements (1,0),(0,1),(1,2) and (0,0)

array([4. , 2. , 6. , 1.5])

In [175]:
b[[1, 0, 1, 0]][:,[0,1,2,0]] #Select a subset of the matrix’s rows and columns


array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

Other Indexing

In [217]:
a = np.arange(100)          # initialization with 0 - 99

In [218]:
a[:3] = 0                   # set the first three indices to zero
a

array([ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [219]:
a[2:5] = 1                  # set indices 2-4 to 1
a

array([ 0,  0,  1,  1,  1,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [220]:
a[:-3] = 2                  # set all but last three elements to 2
a

array([ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 97, 98, 99])

In [224]:
a[None, :]                  # transform to column vector

array([[ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
         2, 97, 98, 99]])

In [223]:
a[[1, 1, 3, 8]]             # return array with values of the indices

array([2, 2, 2, 2])

In [225]:
a = a.reshape(10, 10)       # transform to 10 x 10 matrix
a

array([[ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2, 97, 98, 99]])

In [226]:
a.T                         # return transposed view

array([[ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2, 97],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2, 98],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2, 99]])

In [227]:
b = np.transpose(a, (1, 0)) # transpose array to new axis order

In [232]:
a[a < 2]                    # values with elementwise condition

array([], dtype=int64)

##Array Manipulation

Transposing Array

In [176]:
 i = np.transpose(b) #Permute array dimensions
 i
 

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [177]:
i.T #Permute array dimensions

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

Changing Array Shape

In [178]:
b.ravel() #Flatten the array

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [189]:
h=i
g=b

In [184]:
h.reshape(3,-2) #Reshape, but don’t change data

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])


Adding/Removing Elements

In [187]:
h.resize((1,6)) #Return a new array with shape (2,6)

In [188]:
h

array([[1.5, 2. , 3. , 4. , 5. , 6. ]])

In [190]:
np.append(h,g) #Append items to an array

array([1.5, 2. , 3. , 4. , 5. , 6. , 1.5, 2. , 3. , 4. , 5. , 6. ])

In [191]:
np.insert(a, 1, 5) #Insert items in an array

array([1, 5, 2, 3])

In [192]:
np.delete(a,[1]) #Delete items from an array


array([1, 3])

Combining Arrays

In [193]:
np.concatenate((a,d),axis=0) #Concatenate arrays

array([ 1,  2,  3, 10, 15, 20])

In [194]:
np.vstack((a,b)) #Stack arrays vertically (row-wise)

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [195]:
np.r_[e,f] #Stack arrays vertically (row-wise)

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [196]:
np.hstack((e,f)) #Stack arrays horizontally (column-wise)

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [197]:
np.column_stack((a,d)) #Create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [198]:
np.c_[a,d] #Create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

Splitting Arrays

In [199]:
np.hsplit(a,3) #Split the array horizontally at the 3rd index


[array([1]), array([2]), array([3])]

In [200]:
np.vsplit(c,2) #Split the array vertically at the 2nd index

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
         [4., 5., 6.]]])]

##Array Properties and Operations

In [233]:
a.shape                # a tuple with the lengths of each axis

(10, 10)

In [234]:
len(a)                 # length of axis 0

10

In [235]:
a.ndim                 # number of dimensions (axes)

2

In [238]:
a.sort(axis=1)         # sort array along axis
a

array([[ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2, 97, 98, 99]])

In [237]:
a.flatten()            # collapse array to one dimension

array([ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 97, 98, 99])

In [239]:
a.conj()               # return complex conjugate

array([[ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2, 97, 98, 99]])

In [240]:
a.astype(np.int16)     # cast to integer

array([[ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2, 97, 98, 99]], dtype=int16)

In [241]:
a.tolist()             # convert (possibly multidimensional) array to list

[[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2, 97, 98, 99]]

In [242]:
np.argmax(a, axis=1)   # return index of maximum along a given axis

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 9])

In [243]:
np.cumsum(a)           # return cumulative sum

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 291, 389, 488])

In [244]:
np.any(a)              # True if any element is True

True

In [245]:
np.all(a)              # True if all elements are True

True

In [246]:
np.argsort(a, axis=1)  # return sorted index array along axis

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

## Boolean Arrays

In [252]:
a < 2                         # returns array with boolean values

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [253]:
(a < 2) & (b > 10)            # elementwise logical and

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [254]:
(a < 2) | (b > 10)            # elementwise logical or

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False, False,
         True]])

In [255]:
~a                            # invert boolean array

array([[  -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3],
       [  -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3],
       [  -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3],
       [  -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3],
       [  -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3],
       [  -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3],
       [  -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3],
       [  -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3],
       [  -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3,   -3],
       [  -3,   -3,   -3,   -3,   -3,   -3,   -3,  -98,  -99, -100]])

##linear algebra/ matrix math

In [257]:
evals, evecs = np.linalg.eig(a)      # Find eigenvalues and eigenvectors
evals

array([ 3.55271368e-15+0.00000000e+00j,  1.31320598e+01+0.00000000e+00j,
        1.03867940e+02+0.00000000e+00j,  8.56646981e-16+9.65204888e-16j,
        8.56646981e-16-9.65204888e-16j,  3.80642956e-15+0.00000000e+00j,
       -6.80290433e-31+0.00000000e+00j, -8.30153297e-32+0.00000000e+00j,
       -9.20596868e-47+0.00000000e+00j, -1.97215226e-31+0.00000000e+00j])

In [258]:
evecs

array([[-8.68237346e-01+0.j        ,  2.58853664e-01+0.j        ,
        -2.32349271e-02+0.j        ,  2.47231448e-01+0.29777387j,
         2.47231448e-01-0.29777387j, -7.96143999e-01+0.j        ,
        -3.17147076e-01+0.j        , -6.90071835e-02+0.j        ,
        -1.18734876e-01+0.j        ,  1.10564993e-01+0.j        ],
       [ 1.43964141e-01+0.j        ,  2.58853664e-01+0.j        ,
        -2.32349271e-02+0.j        ,  5.88976623e-01+0.j        ,
         5.88976623e-01-0.j        , -1.27142360e-01+0.j        ,
        -9.52694442e-02+0.j        , -1.99937354e-02+0.j        ,
         4.23171772e-03+0.j        ,  1.26844224e-02+0.j        ],
       [ 1.43964141e-01+0.j        ,  2.58853664e-01+0.j        ,
        -2.32349271e-02+0.j        , -1.58837792e-01-0.54355236j,
        -1.58837792e-01+0.54355236j,  1.41334489e-01+0.j        ,
        -9.24557945e-02+0.j        , -1.93955207e-02+0.j        ,
         4.52583869e-03+0.j        ,  1.20941723e-02+0.j        ],
       

In [260]:
evals, evecs = np.linalg.eigh(a)     # np.linalg.eig for hermitian matrix
evals

array([-9.44241999e+01, -3.30738916e-14, -4.27554840e-15, -2.30304429e-15,
       -5.19748482e-16, -9.86076132e-31,  4.88487159e-15,  1.88560604e-14,
        1.36768504e+01,  1.97747350e+02])

In [261]:
evecs

array([[ 1.05485516e-02, -8.69632422e-01,  4.41900825e-02,
         2.08169432e-02,  1.30700260e-01, -9.55150202e-18,
         2.48960589e-01, -1.39403680e-01,  3.77397038e-01,
        -1.77827858e-02],
       [ 1.05485516e-02,  8.28337022e-02, -4.15241597e-01,
         7.46022834e-01,  5.43859923e-02, -5.22882803e-16,
        -3.37890713e-01, -6.46446491e-02,  3.77397038e-01,
        -1.77827858e-02],
       [ 1.05485516e-02,  4.48572181e-01, -7.27511947e-02,
        -1.09951270e-02,  2.50267942e-01, -1.31772483e-16,
         6.98612570e-01, -3.15942683e-01,  3.77397038e-01,
        -1.77827858e-02],
       [ 1.05485516e-02,  9.84640895e-02,  3.68081079e-01,
         1.24656432e-01,  6.26007125e-02, -1.19554801e-16,
         1.22408111e-01,  8.23118034e-01,  3.77397038e-01,
        -1.77827858e-02],
       [ 1.05485516e-02,  9.22480925e-02,  2.16364488e-02,
        -3.86733235e-01,  2.05777653e-01,  7.07106781e-01,
        -3.83894212e-01, -9.42567046e-02,  3.77397038e-01,
        -1.

## fft

In [264]:
np.fft.fft(a)                # complex fourier transform of a

array([[  20.        +0.00000000e+00j,    0.        +0.00000000e+00j,
           0.        +0.00000000e+00j,    0.        +0.00000000e+00j,
           0.        +0.00000000e+00j,    0.        +0.00000000e+00j,
           0.        +0.00000000e+00j,    0.        +0.00000000e+00j,
           0.        +0.00000000e+00j,    0.        +0.00000000e+00j],
       [  20.        +0.00000000e+00j,    0.        +0.00000000e+00j,
           0.        +0.00000000e+00j,    0.        +0.00000000e+00j,
           0.        +0.00000000e+00j,    0.        +0.00000000e+00j,
           0.        +0.00000000e+00j,    0.        +0.00000000e+00j,
           0.        +0.00000000e+00j,    0.        +0.00000000e+00j],
       [  20.        +0.00000000e+00j,    0.        +0.00000000e+00j,
           0.        +0.00000000e+00j,    0.        +0.00000000e+00j,
           0.        +0.00000000e+00j,    0.        +0.00000000e+00j,
           0.        +0.00000000e+00j,    0.        +0.00000000e+00j,
           0.     

In [266]:
f = np.fft.fftfreq(len(a))   # fft frequencies
f

array([ 0. ,  0.1,  0.2,  0.3,  0.4, -0.5, -0.4, -0.3, -0.2, -0.1])

In [267]:
np.fft.fftshift(f)           # shifts zero frequency to the middle

array([-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4])

In [268]:
np.fft.rfft(a)               # real fourier transform of a

array([[  20.          +0.j        ,    0.          +0.j        ,
           0.          +0.j        ,    0.          +0.j        ,
           0.          +0.j        ,    0.          +0.j        ],
       [  20.          +0.j        ,    0.          +0.j        ,
           0.          +0.j        ,    0.          +0.j        ,
           0.          +0.j        ,    0.          +0.j        ],
       [  20.          +0.j        ,    0.          +0.j        ,
           0.          +0.j        ,    0.          +0.j        ,
           0.          +0.j        ,    0.          +0.j        ],
       [  20.          +0.j        ,    0.          +0.j        ,
           0.          +0.j        ,    0.          +0.j        ,
           0.          +0.j        ,    0.          +0.j        ],
       [  20.          +0.j        ,    0.          +0.j        ,
           0.          +0.j        ,    0.          +0.j        ,
           0.          +0.j        ,    0.          +0.j        ],
     

In [269]:
np.fft.rfftfreq(len(a))      # real fft frequencies

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5])

##Rounding

In [270]:
np.ceil(a)   # rounds to nearest upper int

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2., 97., 98., 99.]])

In [271]:
np.floor(a)  # rounds to nearest lower int

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2., 97., 98., 99.]])

In [272]:
np.round(a)  # rounds to neares int

array([[ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2,  2,  2, 97, 98, 99]])

##random variables

In [274]:
from numpy.random import normal, seed, rand, uniform, randint

In [275]:
normal(loc=0, scale=2, size=100)  # 100 normal distributed

array([-2.46371796, -1.03156787,  0.0121933 , -0.07957604, -0.01589522,
       -1.77203731, -0.63810955,  1.25051578, -0.04927469, -1.77695661,
        0.85466303,  2.40732004,  0.47384026,  2.28313913,  1.34387821,
        2.34121517, -0.38855628,  1.78936369,  2.47960901, -0.96800006,
        0.27253244, -0.29129297,  1.59499561,  0.50657409,  1.85148258,
        4.99416086,  1.5261074 ,  0.38562582,  2.40449205,  0.09682466,
       -1.55399185,  1.24105701,  1.34173877,  0.85702401, -5.08244017,
        4.038681  , -1.63527853, -0.10696563, -0.80309029,  0.68521276,
        3.1943997 , -2.05988716,  1.83299571, -3.30111478, -4.55265833,
        2.16033756,  1.75504302, -1.4806152 , -3.72587386,  1.42220003,
       -0.27307428,  1.16033578,  2.87120945,  2.21409034, -3.94369519,
        6.1962875 , -1.34845602, -0.08115996,  0.35452998, -1.7265815 ,
        3.1441522 ,  0.57135528,  2.24845023, -1.34711003,  3.24682881,
       -3.32899788, -3.07018301, -0.98169583, -0.1566893 , -2.77

In [276]:
seed(23032)                       # resets the seed value

In [277]:
rand(200)                         # 200 random numbers in [0, 1)

array([0.57348412, 0.48893568, 0.19226917, 0.83140393, 0.16324848,
       0.22384859, 0.31019434, 0.98469127, 0.10093018, 0.26468162,
       0.14109166, 0.50023791, 0.15621061, 0.33585395, 0.00894233,
       0.86371038, 0.91503039, 0.76140077, 0.52463803, 0.7433432 ,
       0.20044724, 0.93686076, 0.95852121, 0.11031546, 0.35106453,
       0.8581724 , 0.20178625, 0.06833438, 0.83055122, 0.15816229,
       0.60629502, 0.68568754, 0.28549502, 0.16144249, 0.69888764,
       0.75673814, 0.67790183, 0.89864212, 0.71630523, 0.71271108,
       0.76914465, 0.17481175, 0.43520158, 0.80778973, 0.05457128,
       0.90526927, 0.35085483, 0.95760039, 0.54408281, 0.4217758 ,
       0.4022423 , 0.65001752, 0.92003353, 0.42516503, 0.10160164,
       0.2739798 , 0.54844482, 0.81011269, 0.38102802, 0.20141009,
       0.8911428 , 0.07906593, 0.51324394, 0.51740479, 0.11982671,
       0.55485826, 0.65047857, 0.94853998, 0.02290521, 0.00298936,
       0.5959863 , 0.38074375, 0.70478946, 0.41824626, 0.02322

In [278]:
uniform(1, 30, 200)               # 200 random numbers in [1, 30)

array([19.92262177, 26.96073149,  3.33926073,  1.83293525, 11.25508058,
       22.68808712, 26.1249969 , 23.27272688,  4.12546246,  3.32667604,
        6.7006994 , 24.51830665, 26.01368334, 25.33708537, 29.26542152,
       21.12517498,  5.48480174, 14.46410177, 11.544577  ,  1.46954326,
       27.84765466,  5.76276725,  1.47120921,  7.85081224, 21.76790466,
       29.91060338,  9.18565045, 12.62095322, 23.14588107,  2.46798349,
       20.59100881,  1.1150185 , 29.31541802,  2.18613544,  8.20813912,
       23.47051479,  9.96946118,  4.20775565, 15.91527999, 13.05793185,
        7.49660015, 22.45422757, 28.93065141, 17.65266548, 10.44472637,
       26.88836449, 12.40504872, 20.8567153 , 22.39438351, 27.15861109,
       13.30570471, 21.77923548,  4.39050166, 23.38992276, 20.44909578,
       29.99084365, 15.89378033,  7.0826702 , 23.12865947, 14.09324194,
       26.40513008, 17.65166411, 18.02361187, 12.31836214, 16.13809449,
       10.82823507, 21.10143568, 21.25409809, 12.34052984, 11.92

In [279]:
randint(1, 16, 300)               # 300 random integers in [1, 16)

array([ 8,  9,  3,  9,  2, 15,  3,  2,  3,  2,  8, 11,  1,  2, 14, 13,  3,
        3, 13,  7,  3, 13, 15,  7, 10,  3, 15, 10,  2,  2,  8, 12, 10,  5,
       13, 12, 11, 15,  1, 12,  7,  4,  1, 10, 13,  7,  5, 14,  8, 14, 14,
       15,  8, 14,  4, 11,  5,  7,  5, 12,  7,  1,  5,  7, 14, 14, 10, 12,
       13, 12,  7, 15, 13,  3, 12,  7,  6,  2, 11,  8, 10,  1, 14, 10, 13,
        2, 12,  1,  6, 12,  9,  4,  9,  4,  3,  7, 13, 14, 10,  2,  3,  8,
        1, 10,  4,  5,  3,  1,  4, 10,  6, 14,  2, 14,  1,  6,  3, 11,  1,
        4, 14,  7,  2,  9,  3,  7,  6,  7,  4,  2,  9, 13, 12,  3,  4, 10,
        2,  5, 10, 11, 14,  9, 10,  7,  2, 10,  6, 14,  7,  3,  2, 13,  9,
        4, 10,  4,  3,  7,  3, 15,  7, 12,  5, 13,  9,  2, 10, 11,  2,  1,
       15, 15,  5,  5,  8,  3,  2,  1, 14,  1, 10, 12,  7,  1,  5,  7, 13,
        3,  9,  9,  8,  6,  4,  3, 11,  4,  3,  8,  6, 11, 12,  2,  1,  1,
       13,  5, 14, 12, 12, 10,  7, 12,  4,  9,  2, 12,  9,  9,  6,  8,  2,
        9,  8,  4, 10,  9