<a href="https://colab.research.google.com/github/jgamel/learn_n_dev/blob/data_prep_cleaning/NumPy_Arrays_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy Arrays in Python

Arrays are the main data structure used in machine learning.

n Python, arrays from the NumPy library, called N-dimensional arrays or the ndarray, are used as the primary data structure for representing data.

In this tutorial, you will discover the N-dimensional array in NumPy for representing numerical and manipulating data in Python.

After completing this tutorial, you will know:

1. What the ndarray is and how to create and inspect an array in Python.
2. Key functions for creating new empty arrays and arrays with default values.
3. How to combine existing arrays to create new arrays.



### NumPy N-dimensional Array

NumPy is a Python library that can be used for scientific and numerical applications and is the tool to use for linear algebra operations.

The main data structure in NumPy is the ndarray, which is a shorthand name for N-dimensional array. When working with NumPy, data in an ndarray is simply referred to as an array.

It is a fixed-sized array in memory that contains data of the same type, such as integers or floating point values.

The data type supported by an array can be accessed via the “dtype” attribute on the array. The dimensions of an array can be accessed via the “shape” attribute that returns a tuple describing the length of each dimension. There are a host of other attributes. Learn more here:

A simple way to create an array from data or simple Python data structures like a list is to use the array() function.

The example below creates a Python list of 3 floating point values, then creates an ndarray from the list and access the arrays’ shape and data type.

In [1]:
# create array
from numpy import array
l = [1.0, 2.0, 3.0]
a = array(l)
print(a)
print(a.shape)
print(a.dtype)

[1. 2. 3.]
(3,)
float64


Running the example prints the contents of the ndarray, the shape, which is a one-dimensional array with 3 elements, and the data type, which is a 64-bit floating point.

### Functions to Create Arrays

### Empty
The empty() function will create a new array of the specified shape.

The argument to the function is an array or tuple that specifies the length of each dimension of the array to create. The values or content of the created array will be random and will need to be assigned before use.

The example below creates an empty 3×3 two-dimensional array.

In [2]:
# create empty array
from numpy import empty
a = empty([3,3])
print(a)

[[4.67376131e-310 3.60739284e-313 1.38338381e-322]
 [4.67376131e-310 0.00000000e+000 0.00000000e+000]
 [4.94065646e-323 0.00000000e+000 0.00000000e+000]]


Running the example prints the content of the empty array. Your specific array contents will vary.



### Zeros

The example below creates a 3×5 zero two-dimensional array.

In [3]:
# create zero array
from numpy import zeros
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Running the example prints the contents of the created zero array.

### Ones

The ones() function will create a new array of the specified size with the contents filled with one values.

The argument to the function is an array or tuple that specifies the length of each dimension of the array to create.

The example below creates a 5-element one-dimensional array.

In [4]:
# create one array
from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


### Combining Arrays
NumPy provides many functions to create new arrays from existing arrays.

Let’s look at two of the most popular functions you may need or encounter.

### Vertical Stack
Given two or more existing arrays, you can stack them vertically using the vstack() function.

For example, given two one-dimensional arrays, you can create a new two-dimensional array with two rows by vertically stacking them.

This is demonstrated in the example below.

In [5]:
# vstack
from numpy import array
from numpy import vstack
a1 = array([1,2,3])
print(a1)
a2 = array([4,5,6])
print(a2)
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


Running the example first prints the two separately defined one-dimensional arrays. The arrays are vertically stacked resulting in a new 2×3 array, the contents and shape of which are printed.

### Horizontal Stack
Given two or more existing arrays, you can stack them horizontally using the hstack() function.

For example, given two one-dimensional arrays, you can create a new one-dimensional array or one row with the columns of the first and second arrays concatenated.

This is demonstrated in the example below.

In [6]:
# hstack
from numpy import array
from numpy import hstack
a1 = array([1,2,3])
print(a1)
a2 = array([4,5,6])
print(a2)
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)


Running the example first prints the two separately defined one-dimensional arrays. The arrays are then horizontally stacked resulting in a new one-dimensional array with 6 elements, the contents and shape of which are printed.

### Summary
In this tutorial, you discovered the N-dimensional array in NumPy for representing numerical and manipulating data in Python.

Specifically, you learned:

1. What the ndarray is and how to create and inspect an array in Python.
2. Key functions for creating new empty arrays and arrays with default values.
3. How to combine existing arrays to create new arrays.